### PR TITLE
DCD-889: Add version tag support

### PR DESCRIPTION
**Pull request by tarka**
This adds tags to those resources that support it, and at script to automate updating them.

### CODE REVIEW

**Review by bpar476 — APPROVED** [review]

**Comment by bpar476** [comment]
Is the intention to add these tags to every quick start? Also should we hook up a github action to check that the value is the same as the latest commit?

**Comment by tarka** [comment]
Yep, I'll be adding these to the main quickstart templates.

Checking the commit may be tricky; the hash will never be current, but will  point to the previous commit. In the case of merges there is potentially an ambiguous situation as the merge commit has 2 parents.

One alternative is to have CI do the tagging automatically after each merge, although that can be fiddly (as the act of tagging would cause as new commit, so a new CI run). 

Another option is to add a pre-commit hook to run the update automatically. This would need to be installed by each user though (ideally via `core.hooksPath`).

**Comment by tarka** [comment]
I'm also open to just dropping the commit and just relying on timestamps. Once we get the Ansible tag-on-deployment working we should have the true commit ID available on the instance and auto-scaling group.

**Comment by bpar476** [comment]
> Yep, I'll be adding these to the main quickstart templates.
> 
> Checking the commit may be tricky; the hash will never be current, but will point to the previous commit. In the case of merges there is potentially an ambiguous situation as the merge commit has 2 parents.
> 
> One alternative is to have CI do the tagging automatically after each merge, although that can be fiddly (as the act of tagging would cause as new commit, so a new CI run).
> 
> Another option is to add a pre-commit hook to run the update automatically. This would need to be installed by each user though (ideally via `core.hooksPath`).

Hmm, pre-commit hook sounds like the ideal solution.

**Comment by theghostwhoforks** [comment]
> > Yep, I'll be adding these to the main quickstart templates.
> > Checking the commit may be tricky; the hash will never be current, but will point to the previous commit. In the case of merges there is potentially an ambiguous situation as the merge commit has 2 parents.
> > One alternative is to have CI do the tagging automatically after each merge, although that can be fiddly (as the act of tagging would cause as new commit, so a new CI run).
> > Another option is to add a pre-commit hook to run the update automatically. This would need to be installed by each user though (ideally via `core.hooksPath`).
> 
> Hmm, pre-commit hook sounds like the ideal solution.

There's a story in the backlog to add this - https://pre-commit.com/

**Comment by theghostwhoforks** [comment]
> One alternative is to have CI do the tagging automatically after each merge, although that can be fiddly (as the act of tagging would cause as new commit, so a new CI run).

This should be possible by using skip-ci tags in the commit message. 

Though, the precommit hooks seems to be a cleaner solution?

**Comment by tarka** [comment]
The pre-commit hook it certainly the simplest thing to do. I'll add a low-priority task to add one.

**Pull request merged**
